// Generates src/lib/data/maps.generated.ts — dotted SVG backgrounds and marker
// positions for the MapSelector country/city picker.
//
// Run with: npm run generate:maps
// Re-run only when the regions, markers, or dot styling below change.
// Generation is slow (dotted-map computes every dot), so this is NOT wired
// into predev/prebuild — the output file is committed instead.
import DottedMap from 'dotted-map';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const DOT_STYLE = {
	shape: 'circle',
	backgroundColor: 'transparent',
	color: '#ffd6ec',
	radius: 0.32
};

// Single source of truth for marker coordinates.
// europe-view greece marker + greece-view athens marker share Athens coords.
const MAPS = {
	world: {
		options: { height: 60, grid: 'diagonal' },
		markers: [
			{ id: 'europe', lat: 50, lng: 10 },
			{ id: 'usa', lat: 39.74, lng: -104.99 }, // Denver
			{ id: 'japan', lat: 35.68, lng: 139.69 }, // Tokyo
			{ id: 'mexico', lat: 19.43, lng: -99.13 }, // Mexico City
			{ id: 'australia', lat: -33.87, lng: 151.21 } // Sydney
		]
	},
	europe: {
		options: {
			height: 60,
			grid: 'diagonal',
			region: { lat: { min: 34, max: 62 }, lng: { min: -11, max: 32 } }
		},
		markers: [
			{ id: 'greece', lat: 37.98, lng: 23.72 }, // Athens
			{ id: 'germany', lat: 52.52, lng: 13.4 }, // Berlin
			{ id: 'belgium', lat: 50.85, lng: 4.35 }, // Brussels
			{ id: 'uk', lat: 51.51, lng: -0.13 } // London
		]
	},
	greece: {
		options: { height: 60, grid: 'diagonal', countries: ['GRC'] },
		markers: [
			{ id: 'athens', lat: 37.98, lng: 23.72 },
			{ id: 'thessaloniki', lat: 40.64, lng: 22.94 },
			{ id: 'heraklion', lat: 35.34, lng: 25.14 }
		]
	}
};

const out = {};

for (const [name, { options, markers }] of Object.entries(MAPS)) {
	console.log(`Generating ${name} map...`);
	const map = new DottedMap(options);
	// Render the background BEFORE adding pins so pins don't bake into it.
	const svg = map.getSVG(DOT_STYLE);
	const viewBox = svg.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
	if (!viewBox) throw new Error(`Could not parse viewBox for ${name}`);
	const width = parseFloat(viewBox[1]);
	const height = parseFloat(viewBox[2]);

	out[name] = {
		svg,
		width,
		height,
		markers: markers.map(({ id, lat, lng }) => {
			const pin = map.addPin({ lat, lng, data: id });
			const xPct = (100 * pin.x) / width;
			const yPct = (100 * pin.y) / height;
			if (xPct < 0 || xPct > 100 || yPct < 0 || yPct > 100) {
				throw new Error(`Marker ${id} on ${name} is out of bounds: ${xPct}%, ${yPct}%`);
			}
			console.log(`  ${id}: ${xPct.toFixed(1)}%, ${yPct.toFixed(1)}%`);
			return { id, xPct, yPct };
		})
	};
}

const ts = `// AUTO-GENERATED by scripts/generate-maps.mjs — do not edit by hand.
// Regenerate with: npm run generate:maps

export type MapView = 'world' | 'europe' | 'greece'

export interface MapMarker {
	id: string
	xPct: number
	yPct: number
}

export interface DottedMapData {
	svg: string
	width: number
	height: number
	markers: MapMarker[]
}

export const maps: Record<MapView, DottedMapData> = ${JSON.stringify(out, null, '\t')}
`;

const dest = join(dirname(fileURLToPath(import.meta.url)), '../src/lib/data/maps.generated.ts');
writeFileSync(dest, ts);
console.log(`Wrote ${dest}`);
